---
- name: Ensure directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ base_dir }}"
    - "{{ base_dir }}/logstash"
    - "{{ base_dir }}/logstash/pipeline"

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "/{{ base_dir }}/{{ item.dest }}"
  loop:
    - { src: 'logstash.conf', dest: 'logstash/pipeline/logstash.conf' }
#    - { src: '../../../../docker/elk/docker-stack.yml', dest: 'docker-compose.monitoring.yml' }

