- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 10800

- name: Install required packages
  apt:
    name: [wget, git, vim, curl, gnupg2, ca-certificates, lsb-release, software-properties-common, python3-pip, python3-pymysql, rsyslog, ntp, ntpdate, net-tools]
    state: present

