- hosts: all
  become: true
  roles:
    - common
    - basic
    - containerd

- hosts: master
  become: true
  roles:
    - ha_cluster
    - metallb
    - nerdctl
    - rancher
    - helm
    - traefik

