- hosts: all
  become: true
  roles:
    - common
    - containerd
    - kubeadm

- name: master config
  hosts: master
  become: true
  roles:
    - master

- name: workers config
  hosts: workers
  become: true
  roles:
    - workers

- name: cni_calico
  hosts: master
  become: true
  roles:
    - cni_calico


