- name: Install Node.js LTS
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_24.x | bash -
    apt-get install -y nodejs
  args:
    creates: /usr/bin/node

- name: Check Node version
  command: node -v
  register: node_version
  changed_when: false

- name: Install pnpm globally
  shell: |
    npm install -g pnpm
  args:
    creates: /usr/bin/pnpm

