- name: Setup monitoring infrastructure
  hosts: all
  become: yes
  roles:
    - common

- name: Install node_exporter
  hosts: all
  become: yes
  roles:
    - node_exporter
  when: "'mysql' not in group_names"

- name: Install MySQL exporter
  hosts: mysql
  become: yes
  roles:
    - mysqld_exporter

- name: Install Prometheus
  hosts: prometheus
  become: yes
  roles:
    - prometheus

- name: Install Grafana and dashboards
  hosts: grafana
  become: yes
  roles:
    - grafana

- name: "Issue self-signed SSL Certsficates for domains"
  hosts: traefik
  become: true
  gather_facts: false

  tasks:
    - name: "Include role ssl_cert for each domain"
      include_role:
        name: ssl_cert
      loop: "{{ proxy_domains }}"
      loop_control:
        loop_var: ssl_domain
      vars:
        domain: "{{ ssl_domain }}"

- name: "Install Docker"
  hosts: traefik
  become: true
  roles:
    - docker

- name: "Install/Configure web proxy: traefik"
  hosts: traefik
  become: true
  roles:
    - traefik


