version: "3.9"

services:

  traefik:
    image: traefik:v2.11
    ports:
      - "82:80"
      - "445:443"
      - "8084:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/certs
      - ./logs:/logs
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`traefik.local`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.tls=true"
        #- "traefik.http.routers.dashboard.tls.certresolver=dummy"
        - "traefik.http.services.dummy.loadbalancer.server.port=9999"

  nginx:
    image: nginx:alpine
    networks:
      - web
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sec.rule=Host(`qweasd123.local`) || Host(`phpqwe123.local`)"
        - "traefik.http.routers.sec.entrypoints=websecure"
        - "traefik.http.routers.sec.tls=true"
        - "traefik.http.services.nginx.loadbalancer.server.port=80"

networks:
  web:
    driver: overlay

