ports:
  web:
    port: 80
    expose:
      enabled: true
  websecure:
    port: 443
    expose:
      enabled: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

service:
  enabled: true
  type: LoadBalancer

crds:
  enabled: true

ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true

