global:
  resolve_timeout: 5m

route:
  receiver: 'default'

receivers:
  - name: 'default'
    webhook_configs:
      - url: 'http://alert-webhook:5001/'  # або замість webhook — email/slack

# або, для Telegram через сторонній бот:
#    telegram_configs:
#      - bot_token: 'YOUR_BOT_TOKEN'
#        chat_id: 'YOUR_CHAT_ID'
