global:
  scrape_interval: 20s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  
  - job_name: 'traefik'
    static_configs:
      - targets: ['<traefik-container-ip>:8080']
