global:
  scrape_interval: 20s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']

  - job_name: 'cadvisor'    
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        filters:
          - "label=io.kubernetes.container.name=cadvisor"
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: "container"
      - source_labels: [__meta_docker_container_id]
        target_label: "container_id"
      - source_labels: [__meta_docker_container_name]
        target_label: "service"
      - source_labels: [__meta_docker_task_name]
        target_label: "task"
