global:
  scrape_interval: 20s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  

  - job_name: 'traefik'
    dns_sd_configs:
      - names:
          - 'tasks.task2_flask_traefik'
        type: A
        port: 8080
        
