global:
  scrape_interval: 20s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
      
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8082']

  - job_name: 'cadvisor'    
      docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
    relabel_configs:
      - source_labels: [__meta_docker_container_label_prometheus_job]
        regex: cadvisor
        action: keep
      - source_labels: [__address__]
        target_label: __address__
        regex: '(.*):.*'
        replacement: '${1}:8080'
