- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 10800

- name: Install required packages
  apt:
    name: [wget, git, vim, curl, gnupg2, ca-certificates, lsb-release, software-properties-common, python3-pip, python3-pymysql, certbot, rsyslog, net-tools, zip, unzip]
    state: present

- name: Copy .vimrc
  copy:
    src: ".vimrc"
    dest: "/root/.vimrc"

