http:
  middlewares:
    ratelimit:
      rateLimit:
        average: 10
        burst: 20
    ip-whitelist:
      ipWhiteList:
        sourceRange:
          - "192.168.0.0/24"     # локальна мережа
          - "203.0.113.5/32"     # приклад публічного IP
          - "176.122.123.0/24"
          - "0.0.0.0/0"
        ipStrategy:
          depth: 2     
    dashboard-auth:
      basicAuth:
        users:
          - "admin:$apr1$QSVpkRBZ$1WdzADmkRiJzZBOMeUr.i."  # htpasswd -nb admin <PASSWORD>

  routers:
    dashboard:
      rule: "PathPrefix(`/dashboard`)"
      service: api@internal
      entryPoints:
        - traefik
      middlewares:
        - dashboard-auth

    dashboard-api:
      rule: "PathPrefix(`/api`)"
      service: api@internal
      entryPoints:
        - traefik
      middlewares:
        - dashboard-auth

