log:
  level: ERROR
  filePath: "/logs/traefik.log"

accessLog:
  filePath: "/logs/access.log"

entryPoints:
  web:
    address: "127.0.0.1:80"
    forwardedHeaders:
      insecure: true
      trustedIPs:
        - "127.0.0.1"
        - "::1"
  traefik:
    address: ":8080"
  metrics:
    address: ":8082"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: true
  file:
    directory: /etc/traefik/dynamic
    watch: true


metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

api:
  dashboard: true
  insecure: false

