- name: Deploy Traefik Load Balancer
  hosts: swarm_managers
  become: true
  tags: traefik
  tasks:
    - name: Create directory for Traefik stack
      file:
        path: /opt/traefik-stack
        state: directory
        mode: '0755'

    - name: Copy Traefik docker stack file
      copy:
        src: ../../docker/traefik/docker-stack.yml
        dest: /opt/traefik-stack/docker-stack.yml

    - name: Deploy Traefik stack
      shell: docker stack deploy -c /opt/traefik-stack/docker-stack.yml traefik_stack
      args:
        chdir: /opt/traefik-stack

    - name: Check Traefik services health
      shell: docker service ls --filter label=com.docker.stack.namespace=traefik_stack
      register: traefik_services

    - name: Show Traefik services
      debug:
        var: traefik_services.stdout_lines

    - name: Check Traefik HTTPS service availability
      uri:
        url: "https://{{ traefik_domain }}"
        validate_certs: no
        status_code: 200
        timeout: 10
      register: traefik_response
      retries: 5
      delay: 5
      until: traefik_response.status == 200


