- name: Install Docker
  shell: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
  args:
    creates: /usr/bin/docker

- name: Install Docker Compose plugin (v2)
  shell: |
    curl -SL https://github.com/docker/compose/releases/download/v2.35.1/docker-compose-linux-x86_64 -o /usr/bin/docker-compose
    chmod +x /usr/bin/docker-compose
  args:
    creates: /usr/bin/docker-compose

- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Install Docker Python needed packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-docker
    - python3-jsondiff
    - python3-pretty-yaml

