---
- name: Load kernel modules
  copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
  become: true

- name: Load required modules
  shell: |
    modprobe overlay
    modprobe br_netfilter
  become: true

- name: Set sysctl params for containerd
  copy:
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1
  become: true

- name: Apply sysctl settings
  command: sysctl --system
  become: true

- name: Add Docker GPG key (new format)
  shell: |
    curl -fsSL https://download.docker.com/linux/debian/gpg \
    | gpg --dearmor -o /etc/apt/keyrings/docker-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/docker-apt-keyring.gpg
  become: true

- name: Add Docker repository (using new keyring)
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/docker-apt-keyring.gpg] https://download.docker.com/linux/debian bookworm stable"
    state: present
  become: true

- name: Install containerd
  apt:
    name: containerd.io
    state: present
    update_cache: true
  become: true

- name: Create default containerd config
  command: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml
  become: true

- name: Remove disabled_plugins=["cri"]
  lineinfile:
    path: /etc/containerd/config.toml
    regexp: '^disabled_plugins\s*=\s*\["cri"\]'
    state: absent
  notify: Restart containerd

- name: Ensure CRI section exists
  ansible.builtin.shell: |
    grep '\[plugins."io.containerd.grpc.v1.cri"\]' /etc/containerd/config.toml || \
    containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml
  notify: Restart containerd
  become: true

- name: Restart and enable containerd
  service:
    name: containerd
    state: restarted
    enabled: true
  become: true

- name: Create /etc/crictl.yaml
  copy:
    dest: /etc/crictl.yaml
    content: |
      runtime-endpoint: unix:///run/containerd/containerd.sock
      image-endpoint: unix:///run/containerd/containerd.sock
  become: true

