domain_name: mdb.deus207.pp.ua
domain_root_dir: "/opt/mdb"

mysql_user: "movies_db"

use_ssl: "yes" # no, yes(certbot)
certbot_email: "adm@deus207.pp.ua"

allow_ips:
  - 127.0.0.1
  - 192.168.1.0/24

