- name: Smoke tests for post-deployment
  hosts: all
  become: yes
  tasks:

  - name: Check SSH connectivity
    ping:

- name: Check services on bastion
  hosts: bastion
  become: yes
  tasks:

  - name: Ensure fail2ban is active
    command: systemctl is-active fail2ban
    register: fail2ban_status
    failed_when: fail2ban_status.stdout != "active"
    changed_when: false

  - name: Ensure auditd is active
    command: systemctl is-active auditd
    register: auditd_status
    failed_when: auditd_status.stdout != "active"
    changed_when: false

- name: Check Docker Swarm services
  hosts: web
  become: yes
  tasks:

  - name: Get docker services
    command: docker service ls
    register: services
    changed_when: false

  - name: Print services
    debug:
      var: services.stdout_lines

- name: Check Laravel health
  hosts: web
  tasks:

  - name: Check Laravel HTTP 200 response
    uri:
      url: https://laravel.local
      status_code: 200
      validate_certs: no
      return_content: no

- name: Check Prometheus and Grafana
  hosts: monitoring
  tasks:

  - name: Check Prometheus API
    uri:
      url: http://laravel.local:9090/api/v1/status/runtimeinfo
      status_code: 200

  - name: Check Grafana login page
    uri:
      url: http://laravel.local:3000/login
      status_code: 200

