version: '3.8'

services:
  app:
    build: .
    image: serhiih2025/task-5_laravel:latest
    volumes:
      - .:/var/www
    networks:
      - laravel-public

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "900:80"
    depends_on:
      - app
    networks:
      - laravel-public

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 213402
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-public

volumes:
  db_data:

networks:
  laravel-public:
    external: true

