services:
  app:
    image: serhiih2025/task5_laravel:latest
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == worker]
      restart_policy:
        condition: on-failure
    networks:
      - laravel-public

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - laravel-public

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 213402
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-public

volumes:
  db_data:

networks:
  laravel-public:
    external: true

