pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS = credentials('DockerHub_User_Pass')
        MANAGER_HOST = "192.168.1.188"
    }

    stages {
       stage('Checkout') {
            steps {
                dir('task-1/todo-app') {
                    checkout scm
                }
            }
        }

        stage('Build & Push Images') {
            steps {
                dir('task-1/todo-app') {
                    script {
                        def services = ['web', 'api']
                        for (s in services) {
                            sh """
                                docker build -t ${DOCKERHUB_CREDS_USR}/${s}:latest ./${s}
                                echo $DOCKERHUB_CREDS_PSW | docker login -u $DOCKERHUB_CREDS_USR --password-stdin
                                docker push ${DOCKERHUB_CREDS_USR}/${s}:latest
                            """
                        }
                    }
                }
            }
        }

        stage('Deploy to Swarm') {
            steps {
                dir('task-1/todo-app') {
                    sshagent (credentials: ['swarm-manager-ssh-key']) { // Jenkins credential: "SSH Username with private key"
                        sh """
                            scp -o StrictHostKeyChecking=no docker-compose.yml root@${MANAGER_IP}:/home/ubuntu/
                            ssh -o StrictHostKeyChecking=no root@${MANAGER_IP} 'docker stack deploy -c docker-compose.yml task1'
                        """
                    }
                }
            }
        }
    }
}
