pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS = credentials('DockerHub_User_Pass')
        MANAGER_HOST = "192.168.1.188"
    }

    stages {
       stage('Checkout') {
            steps {
                dir('task-1/todo-app') {
                    checkout scm
                    sh "echo One && pwd && ls -la"
                }
            }
        }

        stage('Build & Push Images') {
            steps {
                dir('task-1/todo-app') {
                    sh "echo Two"
                    sshagent (credentials: ['swarm-manager-ssh-key']) {
                        sh "echo Three"
                        script {
                            def services = [
                                [name: 'task-1_web', path: 'web'],
                                [name: 'task-1_api', path: 'api']
                            ]

                            sh "echo Four && pwd && ls -la"
                            for (s in services) {
                                sh """
                                    ssh -o StrictHostKeyChecking=no root@${MANAGER_HOST} '
                                        cd /root &&
                                        mkdir -p build/${s.path} &&
                                        rm -rf build/${s.path}/*'
                                """

                                echo "📦  SCP ${s.path} → Swarm Manager..."
                                sh """
                                    scp -r -o StrictHostKeyChecking=no ${s.path} root@${MANAGER_HOST}:/root/build/
                                """

                                echo "🛠️  Building image for ${s.name}..."
                                sh """
                                    ssh -o StrictHostKeyChecking=no root@${MANAGER_HOST} '
                                        echo ${DOCKERHUB_CREDS_PSW} | docker login -u ${DOCKERHUB_CREDS_USR} --password-stdin &&
                                        docker build -t ${DOCKERHUB_CREDS_USR}/${s.name}:latest ./build/${s.path} &&
                                        docker push ${DOCKERHUB_CREDS_USR}/${s.name}:latest
                                    '
                                """
                            }
                        }
                    }
                }
            }
        }

        stage('Deploy to Swarm') {
            steps {
                dir('task-1/todo-app') {
                    sshagent (credentials: ['swarm-manager-ssh-key']) { // Jenkins credential: "SSH Username with private key"
                        sh """
                            scp -o StrictHostKeyChecking=no docker-compose.yml root@${MANAGER_HOST}:/root/
                            ssh -o StrictHostKeyChecking=no root@${MANAGER_HOST} 'docker stack deploy -c docker-compose.yml task1'
                        """
                    }
                }
            }
        }
    }
}
