log:
  level: DEBUG # was ERROR
  filePath: "/logs/traefik.log"

accessLog:
  filePath: "/logs/access.log"

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"
  metrics:
    address: ":8082"

#tls:
#  certificates:
#    - certFile: "/certs/selfsigned.crt"
#      keyFile: "/certs/selfsigned.key"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: true

metrics:
  prometheus:
    entryPoint: metrics
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

api:
  dashboard: true
