- name: Check if /root/.my.cnf exists
  stat:
    path: /root/.my.cnf
  register: my_cnf_file

- name: Ensure /root/.my.cnf has correct credentials
  copy:
    dest: /root/.my.cnf
    content: |
      [client]
      user=root
      password={{ db_root_password }}
    mode: '0600'
  when: my_cnf_file.stat.exists == false
  become: yes
  become_user: root

- name: Copy MySQL configuration file
  template:
    src: my.cnf.j2
    dest: /etc/mysql/my.cnf
  notify:
    - Restart MySQL

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Test MySQL connection
  mysql_db:
    name: mysql
    state: present
    login_user: root
    login_password: "{{ db_root_password }}"
    login_unix_socket: "{{ mysql_unix_socket }}"
  become: yes
  become_user: root


