- name: Restart ssh
  service:
    name: ssh
    state: restarted

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: Restart auditd
  service:
    name: auditd
    state: restarted

