traefik_ssl_domains:
  - name: grafana
    domain: grafana.k3s.local
    port: 3000
    namespace: monitoring
  - name: prometheus
    domain: prometheus.k3s.local
    port: 9090
    namespace: monitoring
  - name: traefik
    domain: traefik.k3s.local
    port: 8082
    namespace: kube-system
