all:
  children:
    swarm_managers:
      hosts:
        swarm-manager-2:
          ansible_host: 192.168.1.192

    swarm_workers:
      hosts:
        swarm-worker-1:
          ansible_host: 192.168.1.189

    bastion:
      hosts:
        bastion-1:
          ansible_host: 192.168.1.197



  vars:
    - ansible_user=devops
    - ansible_ssh_private_key_file=~/.ssh/id_rsa

