- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 10800

- name: Install common packages
  apt:
    name:
      - apt-transport-https
      - software-properties-common
      - ca-certificates
      - vim
      - sudo
      - curl
      - git
      - htop
      - unzip
      - ufw
      - wget
      - jq
      - tree
      - rsyslog
      - net-tools
      - python3-pip
      - python3-venv
      - pkg-config
      - build-essential
      - default-libmysqlclient-dev
    state: present

- name: Copy .vimrc
  copy:
    src: ".vimrc"
    dest: "/root/.vimrc"

- name: Setup timezone to Kyiv
  timezone:
    name: Europe/Kyiv

