- name: Download Helm install script
  get_url:
    url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    dest: /tmp/get_helm.sh
    mode: '0755'

- name: Run Helm install script
  shell: /tmp/get_helm.sh
  args:
    creates: /usr/local/bin/helm

- name: Check helm version
  command: helm version
  register: helm_version
  changed_when: false

- debug:
    var: helm_version.stdout

