{
 "title": "Docker and system monitoring",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "containergroup",
    "label": "Container Group",
    "query": {
     "query": "label_values(container_label_com_docker_compose_project)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "Node",
    "query": {
     "query": "label_values(node_boot_time_seconds, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"$server:.*\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{name=~\"$containergroup.+\"})",
     "legendFormat": "Containers"
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min((node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$server:.*\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"$server:.*\"} )/ node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$server:.*\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$server:.*\"} - node_memory_MemAvailable_bytes{instance=~\"$server:.*\"}) / node_memory_MemTotal_bytes{instance=~\"$server:.*\"}) * 100",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~'$server:.*'} - node_memory_SwapFree_bytes{instance=~'$server:.*'})"
    }
   ]
  },
  {
   "title": "Load",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1-(avg without(cpu,instance,mode) (rate(node_cpu_seconds_total{instance=~\"$server:.*\",mode=\"idle\"}[$interval])))",
     "legendFormat": "1m Load Average"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "- sum(rate(node_network_receive_bytes_total{instance=~\"$server:.*\"}[$interval])) ",
     "legendFormat": "RECEIVED"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$server:.*\"}[$interval])) ",
     "legendFormat": "SENT"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{instance=~\"$server:.*\"}[$interval])) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1-(avg without(cpu,instance,mode) (rate(node_cpu_seconds_total{instance=~\"$server:.*\",mode=\"idle\"}[$interval])))",
     "legendFormat": "Load Average"
    }
   ]
  },
  {
   "title": "Used Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype=\"ext4\",instance=~\"$server:.*\"} - node_filesystem_free_bytes{fstype=\"ext4\",instance=~\"$server:.*\"}",
     "legendFormat": "Used Disk Space"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$server:.*\"}",
     "legendFormat": "Available Memory"
    },
    {
     "expr": "node_memory_MemTotal - node_memory_MemAvailable",
     "legendFormat": "Unavailable Memory"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "-sum(rate(node_disk_read_bytes_total{instance=~\"$server:.*\"}[$interval])) by (device)",
     "legendFormat": "OUT on /{{device}}"
    },
    {
     "expr": "sum(rate(node_disk_written_bytes_total{instance=~\"$server:.*\"}[$interval])) by (device)",
     "legendFormat": "IN on /{{device}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\"$containergroup.+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\"$containergroup.+\"}[$interval])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"$containergroup.+\"}[$interval])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_swap{name=~\"$containergroup.+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=~\"$containergroup.+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Limit memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_spec_memory_limit_bytes{name=~\"$containergroup.+\"}) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Usage memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name=~\"$containergroup.+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Remaining memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(100 - ((container_spec_memory_limit_bytes{name=~\"$containergroup.+\"} - container_memory_usage_bytes{name=~\"$containergroup.+\"})  * 100 / container_spec_memory_limit_bytes{name=~\"$containergroup.+\"}) ) by (name) ",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}