- name: Install auditd
  apt:
    name: auditd
    state: present
    update_cache: no

- name: Deploy custom audit rules
  template:
    src: audit.rules.j2
    dest: /etc/audit/rules.d/audit.rules
    owner: root
    group: root
    mode: '0600'
  notify: Restart auditd

- name: Deploy logrotate config for audit logs
  template:
    src: auditd.logrotate.j2
    dest: /etc/logrotate.d/audit
    owner: root
    group: root
    mode: '0644'

- name: Ensure auditd is enabled and running
  service:
    name: auditd
    enabled: yes
    state: started

