- name: Stop MariaDB service
  ansible.builtin.service:
    name: mariadb
    state: stopped

- name: Ensure skip-grant-tables is set under [mysqld]
  ansible.builtin.lineinfile:
    path: /etc/mysql/my.cnf
    insertafter: '^\[mysqld\]'
    line: 'skip-grant-tables'
    state: present

- name: Ensure skip-networking is set under [mysqld]
  ansible.builtin.lineinfile:
    path: /etc/mysql/my.cnf
    insertafter: '^\[mysqld\]'
    line: 'skip-networking'
    state: present

- name: Start MariaDB with skips
  ansible.builtin.service:
    name: mariadb
    state: started

- name: Fix root users inside MariaDB
  ansible.builtin.shell: |
    mariadb -e "
    FLUSH PRIVILEGES;
    DROP USER IF EXISTS 'root'@'localhost';
    CREATE USER 'root'@'localhost' IDENTIFIED BY '{{ mysql_root_password }}';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;

    DROP USER IF EXISTS 'root'@'%';
    CREATE USER 'root'@'%' IDENTIFIED BY '{{ mysql_root_password }}';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

    FLUSH PRIVILEGES;
    "
  args:
    executable: /bin/bash

- name: Stop MariaDB after fix
  ansible.builtin.service:
    name: mariadb
    state: stopped

- name: Remove skip-grant-tables option
  ansible.builtin.lineinfile:
    path: /etc/mysql/my.cnf
    line: 'skip-grant-tables'
    state: absent

- name: Remove skip-networking option
  ansible.builtin.lineinfile:
    path: /etc/mysql/my.cnf
    line: 'skip-networking'
    state: absent

- name: Start MariaDB cleanly
  ansible.builtin.service:
    name: mariadb
    state: started

#- name: Show final privileges
#  community.mysql.mysql_query:
#    query: "SELECT User, Host, JSON_EXTRACT(Priv, '$.access') AS access FROM mysql.global_priv WHERE User='root';"
#    login_unix_socket: /run/mysqld/mysqld.sock
#  register: final_root_privs

#- name: Display final root privileges
#  debug:
#    var: final_root_privs.query_result


