---
- name: ELK: Ensure directories exist 
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ base_dir }}"
    - "{{ base_dir }}/elk"

- name: ELK: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "/{base_dir}/{{ item.dest }}"
  loop:
    - { src: 'docker-stack.yml', dest: 'docker-stack.yml' }

- name: Deploy ELK stack
  shell: docker stack deploy -c docker-stack.yml elk
  args:
    chdir: {{ base_dir }}/elk

- name: Check ELK services health
  shell: docker service ls --filter label=com.docker.stack.namespace=elk
  register: elk_services

- name: Show ELK services
  debug:
    var: elk_services.stdout_lines

- name: Check Kibana HTTP service availability
  uri:
    url: "http://{{ kibana_domain }}:5601"
    status_code: 200
    timeout: 10
  register: kibana_response
  retries: 5
  delay: 5
  until: kibana_response.status == 200

