---
- name: Ensure directories exist 
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ base_dir }}"
    - "{{ base_dir }}/elk"

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "/{{ base_dir }}/{{ item.dest }}"
  loop:
    - { src: 'docker-stack.yml', dest: 'docker-stack-elk.yml' }



