- name: Awstats
  hosts: all
  become: yes
  vars:
    - awstats_domain: voc.deus207.pp.ua
    - nginx_log_file: /var/log/nginx/voc.deus207.pp.ua_access.log
  roles:
    - install
    - awstats_nginx
    - config_domain

