- name: Ensure certs directory exists
  file:
    path: "{{ cert_dir }}"
    state: directory
    mode: '0755'

- name: Check if certificate file exists
  stat:
    path: "{{ cert_dir }}/{{ domain }}.crt"
  register: cert_stat

- name: Check if key file exists
  stat:
    path: "{{ cert_dir }}/{{ domain }}.key"
  register: key_stat

- name: Get certificate modulus hash
  shell: |
    openssl x509 -noout -modulus -in {{ cert_dir }}/{{ domain }}.crt | openssl sha256
  register: cert_modulus
  when: cert_stat.stat.exists
  changed_when: false
  ignore_errors: true

- name: Get key modulus hash
  shell: |
    openssl rsa -noout -modulus -in {{ cert_dir }}/{{ domain }}.key | openssl sha256
  register: key_modulus
  when: key_stat.stat.exists
  changed_when: false
  ignore_errors: true

- name: Generate new self-signed cert and key if missing or invalid
  command: >
    openssl req -x509 -newkey rsa:4096 -nodes
    -keyout {{ cert_dir }}/{{ domain }}.key
    -out {{ cert_dir }}/{{ domain }}.crt
    -days 365
    -subj "/CN={{ domain }}"
    -addext "subjectAltName=DNS:{{ domain }}"
  when: not cert_stat.stat.exists
        or not key_stat.stat.exists
        or cert_modulus.stdout != key_modulus.stdout

- name: Slurp certificate file
  slurp:
    src: "{{ cert_dir }}/{{ domain }}.crt"
  register: traefik_crt

- name: Slurp key file
  slurp:
    src: "{{ cert_dir }}/{{ domain }}.key"
  register: traefik_key

- name: Create TLS secret for Traefik
  kubernetes.core.k8s:
    state: present
    namespace: kube-system
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: traefik-tls
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ traefik_crt.content }}"
        tls.key: "{{ traefik_key.content }}"

