services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - django_net

  web:
    image: serhiih2025/task-3_django:latest
    volumes:
      - .:/app
    depends_on:
      - db
      - traefik
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.django.rule=Host(`django.local`)"
        - "traefik.http.routers.django.entrypoints=web"
        - "traefik.http.services.django.loadbalancer.server.port=8000"
    networks:
      - django_net
    environment:
      DEBUG: '1'
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: todo_pass
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: "f439fh349ufg93fb08y43fvgyiufuy0sdgf0834ufgy0wefgdiusfbu"

  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "8080:8080"
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/logs:/logs
      - /etc/certs:/certs
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`traefik.django.local`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
        - "traefik.http.routers.traefik.entrypoints=dashboard"
        - "traefik.http.routers.traefik.service=api@internal"
    networks:
      - django_net

volumes:
  postgres_data:

networks:
  django_net:
    driver: overlay
