services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task3_django

  web:
    image: serhiih2025/task-3_django:latest
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: '1'
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: todo_pass
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: "f439fh349ufg93fb08y43fvgyiufuy0sdgf0834ufgy0wefgdiusfbu"
    networks:
      - task3_django

volumes:
  postgres_data:

networks:
  task3_django:
    external: true
