services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - task3_django

  django:
    image: serhiih2025/task-3_django:latest
    volumes:
      - .:/app
    depends_on:
      - db
      - traefik
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.django.rule=Host(`django.local`)"
        - "traefik.http.routers.flask.entrypoints=websecure"
        - "traefik.http.routers.flask.tls=true"
        - "traefik.http.routers.flask.service=django"
        - "traefik.http.services.django.loadbalancer.server.port=8000"
    networks:
      - task3_django
    environment:
      DEBUG: '1'
      DB_NAME: todo_db
      DB_USER: todo_user
      DB_PASSWORD: todo_pass
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: "f439fh349ufg93fb08y43fvgyiufuy0sdgf0834ufgy0wefgdiusfbu"

  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/logs:/logs
      - /etc/certs:/certs
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - task3_django
      - monitoring

volumes:
  postgres_data:

networks:
  task3_django:
    external: true
  monitoring:
    external: true
