all:
  children:
    master:
      hosts:
        master1:
          ansible_host: 192.168.1.180
        master2:
          ansible_host: 192.168.1.188
        master3:
          ansible_host: 192.168.1.189
    workers:
      hosts:
        worker1:
          ansible_host: 192.168.1.186

