- name: Create first database
  mysql_db:
    name: mydb
    state: present

- name: Create second database
  mysql_db:
    name: db2
    state: present

- name: Remove database test
  mysql_db:
    name: test
    state: absent

- name: Set other master's IP based on inventory
  ansible.builtin.set_fact:
    mysql_master_host: "{{ hostvars[item].ansible_host }}"
  loop: "{{ groups['mysql_servers'] }}"
  when: item != inventory_hostname

- name: Ensure replication user exists
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    name: replica
    password: "{{ mysql_replica_password }}"
    host: "%"
    priv: "*.*:REPLICATION SLAVE,REPLICATION CLIENT"
    state: present

- name: Stop MySQL server
  ansible.builtin.systemd:
    name: mysql
    state: stopped

- name: Ensure replication settings in my.cnf under [mysqld]
  ansible.builtin.lineinfile:
    path: /etc/mysql/my.cnf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: '^\[mysqld\]'
    state: present
  loop:
    - { regexp: '^server-id=', line: "server-id={{ server_id }}" }
    - { regexp: '^auto_increment_increment=', line: "auto_increment_increment=2" }
    - { regexp: '^auto_increment_offset=', line: "auto_increment_offset={{ server_id }}" }
    - { regexp: '^log_bin=', line: "log_bin=mysql-bin" }
    - { regexp: '^binlog_do_db=mydb$', line: "binlog_do_db=mydb" }
    - { regexp: '^binlog_do_db=db2$', line: "binlog_do_db=db2" }
    - { regexp: '^gtid_strict_mode=', line: "gtid_strict_mode=ON" }
    - { regexp: '^log_slave_updates=', line: "log_slave_updates=ON" }
    - { regexp: '^read_only=', line: "read_only=OFF" }
    - { regexp: '^expire_logs_days=', line: "expire_logs_days=3" }
    - { regexp: '^max_binlog_size=', line: "max_binlog_size=1024M" }
    - { regexp: '^replicate-do-db=mydb$', line: "replicate-do-db=mydb" }
    - { regexp: '^replicate-do-db=db2$', line: "replicate-do-db=db2" }


- name: Start MySQL server
  ansible.builtin.systemd:
    name: mysql
    state: started
    enabled: true


