- name: Apply common things
  hosts: all
  become: yes
  roles:
    - common

- name: Setup K3s Master
  hosts: master
  become: yes
  roles:
    - k3s_server

- name: Setup K3s Workers
  hosts: workers
  become: yes
  roles:
    - k3s_agent

