pipeline {
    agent any

    environment {
        DOCKERHUB_USER = credentials('serhiih2025')
        DOCKERHUB_PASS = credentials('DiavCRvPw-Lf')
        MANAGER_HOST = "192.168.1.188"
        SSH_KEY = credentials('swarm-ssh-key') // Jenkins credential: "SSH Username with private key"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git 'https://github.com/your/repo.git'
            }
        }

        stage('Build & Push Images') {
            steps {
                script {
                    def services = ['web', 'api']
                    for (s in services) {
                        sh """
                            docker build -t ${DOCKERHUB_USER}/${s}:latest ./${s}
                            echo $DOCKERHUB_PASS | docker login -u $DOCKERHUB_USER --password-stdin
                            docker push ${DOCKERHUB_USER}/${s}:latest
                        """
                    }
                }
            }
        }

        stage('Deploy to Swarm') {
            steps {
                sshagent (credentials: ['swarm-ssh-key']) {
                    sh """
                        scp -o StrictHostKeyChecking=no docker-compose.yml ${env.MANAGER_HOST}:/home/ubuntu/
                        ssh -o StrictHostKeyChecking=no ubuntu@${env.MANAGER_HOST} 'docker stack deploy -c docker-compose.yml myapp'
                    """
                }
            }
        }
    }
}
