---
- name: Fetch join command from master
  slurp:
    src: /tmp/kubeadm_join_cmd.sh
  register: join_script_encoded
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

- name: Decode join command
  set_fact:
    join_command: "{{ join_script_encoded.content | b64decode }}"

- name: Run kubeadm join
  command: "{{ join_command }}"
  args:
    creates: /etc/kubernetes/kubelet.conf
  become: true

