- name: "Setup LEMP environment"
  hosts: all
  become: true

  roles:
    - role: common
    - role: ssl
      vars:
        domain: "app1.tst.local"

    - role: php
    - role: nginx
    - role: mysql

