- name: Disable SWAP
  ansible.builtin.command: swapoff -a
  become: true

- name: Remove SWAP entry from /etc/fstab
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*swap.*)$'
    replace: '# \1'
  become: true

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 10800
  become: true

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - software-properties-common
      - ca-certificates
      - curl
      - wget
      - vim
      - git
      - gnupg
      - lsb-release
      - ntp
      - ntpdate
      - jq
    state: present
  become: true

- name: Copy .vimrc
  copy:
    src: ".vimrc"
    dest: "/root/.vimrc"
  become: true

- name: Setup timezone to Kyiv
  timezone:
    name: Europe/Kyiv
  become: true

- name: Enable and start NTP service
  service:
    name: ntp
    enabled: true
    state: started
  become: true

- name: Set sysctl params for Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  become: true

- name: Apply sysctl params
  command: sysctl --system
  become: true

