version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    ports:
      - 9100:9100
    deploy:
      restart_policy:
        condition: on-failure
    networks:
      - monitoring
      
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./grafana/datasources:/etc/grafana/provisioning/datasources

volumes:
  grafana-storage:

networks:
  monitoring:
    external: true
