ports:
  web:
    expose:
      default: true
  websecure:
    expose:
      default: true

service:
  enabled: true
  type: LoadBalancer
  ports:
    web:
      port: 80
    websecure:
      port: 443

crds:
  enabled: true

ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesIngress:
    publishedService:
      enabled: true

