services:
  goapp:
    image: serhiih2025/task-4_goapp:latest
    depends_on:
      - traefik
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.goapp.rule=Host(`go.local`)"
        - "traefik.http.routers.goapp.service=goapp"
        - "traefik.http.routers.goapp.tls=true"
        - "traefik.http.routers.goapp.entrypoints=websecure"
        - "traefik.http.services.goapp.loadbalancer.server.port=4000"
        - "traefik.http.routers.goapp.middlewares=ratelimit@file,ip-whitelist@file"
        - "traefik.docker.network=goapp-public"
    environment:
      - PORT=4000
    networks:
      - goapp-public

  traefik:
    image: traefik:v2.10
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "8080:8080"
      - "8082:8082"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro
      - ./traefik/logs:/logs
      - /etc/certs:/certs
    networks:
      - goapp-public
      - monitoring

networks:
  goapp-public:
    external: true
  monitoring:
    external: true
