services:
  goapp:
    image: serhiih2025/task-4_go:latest
    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.goapp.rule=Host(`go.local`)"
        - "traefik.http.routers.goapp.entrypoints=websecure"
        - "traefik.http.routers.goapp.tls.certresolver=letsencrypt"
        - "traefik.http.services.goapp.loadbalancer.server.port=4000"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
