version: "3.9"

services:
  flask:
    image: serhiih2025/flask-app:latest
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.flask.rule=Host(`flask.local`)"
        - "traefik.http.routers.flask.entrypoints=http"
        - "traefik.http.services.flask.loadbalancer.server.port=5000"
    networks:
      - traefik-net

  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.dashboard=true"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
      - "--api.insecure=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
#      - "--providers.docker.exposedbydefault=false"
#      - "--entrypoints.http.address=:80"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    deploy:
      placement:
        constraints: 
          - node.role == manager
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
