version: "3.9"

services:
  flask:
    image: serhiih2025/flask-app:latest
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.flask.rule=Host(`flask.local`)"
        - "traefik.http.routers.flask.entrypoints=websecure"
        - "traefik.http.routers.flask.tls=true"
        - "traefik.http.routers.flask.service=flask"
        - "traefik.http.services.flask.loadbalancer.server.port=5000"
    networks:
      - traefik-net

  traefik:
    image: traefik:v2.10
    command: []
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /root/build/task-2/flask-app/traefik.yml:/etc/traefik/traefik.yml:ro
      - /root/build/task-2/flask-app/logs:/logs
      - /etc/certs:/certs
    deploy:
      placement:
        constraints: 
          - node.role == manager
    networks:
      - traefik-net
      - monitoring

networks:
  traefik-net:
    external: true
  monitoring:
    external: true
