log:
  level: ERROR
  filePath: "/logs/traefik.log"

accessLog:
  filePath: "/logs/access.log"

entryPoints:
  http:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false # was true
    swarmMode: true

metrics:
  prometheus: {}

api:
  dashboard: true
  insecure: true

  
