log:
  level: ERROR
  filePath: "/logs/traefik.log"

accessLog:
  filePath: "/logs/access.log"

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    swarmMode: true
