log:
  level: ERROR
  filePath: "/logs/traefik.log"

accessLog:
  filePath: "/logs/access.log"

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: selfsigned

tls:
  certificates:
    - certFile: "/certs/selfsigned.crt"
      keyFile: "/certs/selfsigned.key"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: true

metrics:
  prometheus: {}

api:
  dashboard: true
  insecure: true
