---
- name: Create kubeadm config file
  template:
    src: kubeadm-config.yaml.j2
    dest: /root/kubeadm-config.yaml
  become: true

- name: Migrate kubeadm config to new version
  command: kubeadm config migrate --old-config=/root/kubeadm-config.yaml --new-config=/root/kubeadm-config-new.yaml
  args:
    creates: /root/kubeadm-config-new.yaml
  become: true

- name: Initialize Kubernetes cluster
  command: kubeadm init --config=/root/kubeadm-config.yaml
#  command: kubeadm init --config=/root/kubeadm-config-new.yaml  #for 1.33+
  args:
    creates: /etc/kubernetes/admin.conf
  become: true
  register: kubeadm_init

#- name: Show kubeadm init output
#  ansible.builtin.debug:
#    var: kubeadm_init.stdout_lines

- name: Set up kubeconfig for root
  shell: |
    mkdir -p /root/.kube
    cp -i /etc/kubernetes/admin.conf /root/.kube/config
    chown root:root /root/.kube/config
  args:
    creates: /root/.kube/config
  become: true

- name: Extract join command
  shell: kubeadm token create --print-join-command
  register: join_command
  changed_when: false
  become: true

- name: Save join command to file
  copy:
    content: "{{ join_command.stdout }}"
    dest: /tmp/kubeadm_join_cmd.sh
    mode: '0644'
  become: true

