all:
  children:
    zabbix_server:
      hosts:
        zabbix1:
          ansible_host: 192.168.1.184
    zabbix_api:
      hosts:
        localhost:
          ansible_connection: httpapi
          ansible_httpapi_use_ssl: false
          ansible_httpapi_validate_certs: false
          ansible_network_os: community.zabbix.zabbix
          ansible_user: Admin
          ansible_password: zabbix
          ansible_host: 192.168.1.184
    monitoring:
      hosts:
        prometheus:
          ansible_host: 192.168.1.182
        grafana:
          ansible_host: 192.168.1.181
    mysql:
      hosts:
        mysql1:
          ansible_host: 192.168.1.193
        mysql2:
          ansible_host: 192.168.1.194
    app:
      hosts:
        lemp1:
          ansible_host: 192.168.1.180
    traefik_docker:
      hosts:
        traefik1:
          ansible_host: 192.168.1.183
    jenkins:
      hosts:
        jenkins1:
          ansible_host: 192.168.1.187
