---
- name: Download Calico manifest
  get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v3.29.3/manifests/calico.yaml
    dest: /root/calico.yaml
    mode: '0644'
  become: true

- name: Un-comment CALICO_IPV4POOL_CIDR env variable name
  replace:
    path: /root/calico.yaml
    regexp: '^\s*#\s*(- name: CALICO_IPV4POOL_CIDR)'
    replace: '            \1'
  become: true

- name: Set CALICO_IPV4POOL_CIDR value
  replace:
    path: /root/calico.yaml
    regexp: '^\s*#\s*value:\s*".*"'
    replace: '              value: "{{ calico_ipv4pool_cidr }}"'
  vars:
    calico_ipv4pool_cidr: "10.60.0.0/16"
  become: true

- name: Apply Calico network plugin
  command: kubectl apply -f /root/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  become: true

