- name: Create traefik directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "deployer"
    group: "deployer"
    mode: 0755
  loop:
    - "/home/deployer/traefik"
    - "/home/deployer/traefik/logs"
    - "/home/deployer/traefik/config"
    - "/home/deployer/traefik/config/dynamic"

- name: Upload traefik dynamic config
  copy:
    src: dynamic.yml
    dest: "/home/deployer/traefik/config/dynamic/dynamic.yml"
    owner: "deployer"
    group: "deployer"
    mode: 0644

- name: Upload traefik static config
  copy:
    src: traefik.yml
    dest: "/home/deployer/traefik/config/traefik.yml"
    owner: "deployer"
    group: "deployer"
    mode: 0644

- name: Upload traefik docker stack conofig
  template:
    src: traefik-stack.yml.j2
    dest: "/home/deployer/traefik/traefik-stack.yml"
    owner: "deployer"
    group: "deployer"
    mode: 0644

- name: Ensure global overlay network exists
  docker_network:
    name: global_net
    driver: overlay
    scope: swarm
    attachable: yes
    state: present

- name: Deploy Traefik stack
  docker_stack:
    name: traefik
    state: present
    compose:
      - /home/deployer/traefik/traefik-stack.yml

