---
- name: Update apt
  apt:
    update_cache: yes
    cache_valid_time: 10800

- name: Install required packages
  apt:
    name:
      - build-essential
      - autotools-dev
      - libpcap-dev
      - libpcre3-dev
      - libdumbnet-dev
      - bison
      - flex
      - rsyslog
      - zlib1g-dev
      - liblzma-dev
      - openssl
      - libssl-dev
      - libpcre2-dev
      - libnghttp2-dev
      - libhwloc-dev
      - cmake
      - libluajit-5.1-dev
      - pkg-config
      - libmnl-dev
      - libunwind-dev
      - libnetfilter-queue-dev
      - git
      - python3-pip
    state: present

