- name: Install dependencies
  import_tasks: deps.yml

#- name: Build libdaq
#  import_tasks: libdaq.yml
#
#- name: Download and extract Snort
#  import_tasks: download.yml
#
#- name: Build and install Snort
#  import_tasks: build.yml

- name: Configure directories and permissions
  import_tasks: config.yml

- name: Deploy test rule
  import_tasks: test_rule.yml

- name: Install pulledpork
  import_tasks: pulledpork.yml

- name: Apply rules
  import_tasks: rules.yml

- name: Set up Snort systemd service
  import_tasks: service.yml

