- name: Update Snort rules using PulledPork
  command: >
    /usr/local/bin/pulledpork3 -c /etc/snort/pulledpork.conf
  register: pulledpork_result

- name: Unite test.rules and snort.rules in combined.rules
  shell: >
    cat /etc/snort/rules/local.rules /etc/snort/rules/snort.rules > /etc/snort/rules/combined.rules

- name: Remove rules with sid 105, 108, 115 from combined.rules
  shell: >
    sed -i '/sid:105;/d; /sid:108;/d; /sid:115;/d' /etc/snort/rules/combined.rules

