- name: Update Snort rules using PulledPork
  command: >
    /usr/local/bin/pulledpork3 -c /etc/snort/pulledpork.conf
  register: pulledpork_result

- name: Show update result
  debug:
    msg: "{{ pulledpork_result.stdout_lines }}"

#- name: Fix bad Snort 3 rules syntax with double port vars
#  replace:
#    path: /etc/snort/rules/snort.rules
#    regexp: '\$HTTP_SERVERS\s+\$HTTP_PORTS'
#    replace: '$HTTP_SERVERS any'
#
#- name: Replace bad destination port syntax in Snort rules
#  replace:
#    path: /etc/snort/rules/snort.rules
#    regexp: '\$HOME_NET\s+\$HTTP_PORTS'
#    replace: 'any $HTTP_PORTS'


