- name: Add Helm repo for Traefik
  shell: helm repo add traefik https://traefik.github.io/charts && helm repo update
  args:
    creates: /tmp/traefik_repo_added

- name: Install or upgrade Traefik via Helm
  kubernetes.core.helm:
    name: traefik
    chart_ref: traefik/traefik
    release_namespace: kube-system
    create_namespace: false
    values: "{{ lookup('file', 'traefik-values.yaml') | from_yaml }}"
    wait: true
    update_repo_cache: true

- name: Create IngressRoute for Traefik dashboard
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      metadata:
        name: traefik-dashboard
        namespace: kube-system
      spec:
        entryPoints:
          - web
          - websecure
        routes:
          - match: Host(`traefik.k3s.local`)
            kind: Rule
            services:
              - name: api@internal
                kind: TraefikService
            middlewares:
              - name: redirect-https
        tls:
          secretName: "traefik-tls"
