ports:
  web:
    port: 80
    expose:
      enabled: true
  websecure:
    port: 443
    expose:
      enabled: true

service:
  enabled: true
  type: LoadBalancer

crds:
  enabled: true

ingressRoute:
  dashboard:
    enabled: true

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true

