all:
  children:
    monitoring:
      hosts:
        prometheus:
          ansible_host: 192.168.1.182
        grafana:
          ansible_host: 192.168.1.181
    mysql:
      hosts:
        mysql1:
          ansible_host: 192.168.1.193
        mysql2:
          ansible_host: 192.168.1.194
    app:
      hosts:
        app1:
          ansible_host: 192.168.1.180

