global:
  scrape_interval: 20s
  evaluation_interval: 20s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']

  - job_name: 'traefik'
    metrics_path: /metrics
    static_configs:
      - targets: ['traefik:8082']


