- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 10800

- name: Install required packages
  apt:
    name: [wget, git, vim, curl, gnupg2, ca-certificates, lsb-release, software-properties-common, apt-transport-https, python3-pip, python3-pymysql, rsyslog, ntp, ntpdate, net-tools, tree]
    state: present

- name: Copy .vimrc
  copy:
    src: ".vimrc"
    dest: "/root/.vimrc"

- name: Setup timezone to Kyiv
  timezone:
    name: Europe/Kyiv

- name: Ensure NTP is running
  service:
    name: ntp
    state: started
    enabled: yes

