version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      labels:
        # redirect HTTP => HTTPS by traefik dynamic.yml
        - "traefik.enable=true"
        - "traefik.http.routers.prometheus.rule=Host(`prometheus.tst.local`)"
        - "traefik.http.routers.prometheus.entrypoints=websecure"
        - "traefik.http.routers.prometheus.tls=true"
        - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
    ports:
      - "9090:9090"
    networks:
      - global_net

  grafana:
    image: grafana/grafana
    user: "472"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=213402
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana-insecure.rule=Host(`grafana.tst.local`)"
        - "traefik.http.routers.grafana-insecure.entrypoints=web"
        - "traefik.http.routers.grafana-insecure.middlewares=redirect-to-https"

        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

        - "traefik.http.routers.grafana.rule=Host(`grafana.tst.local`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls=true"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    ports:
      - "3000:3000"
    networks:
      - global_net

  node-exporter:
    image: prom/node-exporter
    deploy:
      mode: global
    networks:
      - global_net
    ports:
      - "9100:9100"


volumes:
  grafana-storage:

networks:
  global_net:
    external: true

